# Profile information
name: SciPySP
title: Somos o grupo de Python Cientifico em São Paulo
description: > # this means to ignore newlines until "baseurl:"
  SciPy (pronuncia-se 'Sai Pai') é um ecossistema open-source baseado em Python para matemática, ciências e engenharia.
permalink: ':title/'
baseurl: "/fresh" # the subpath of your site, e.g. /blog
url: "scipy-sp.gitpages.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social
facebook: https://www.facebook.com/SciPySP/
twitter: https://twitter.com/SciPySP
#google-plus: #Add your Google+
github: https://github.com/SciPy-SP

# Contact form
email: contato@sp.scipy.org.br

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
